version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  strapi:
    image: node:22
    working_dir: /srv/app
    volumes:
      - ./edx-strapi:/srv/app
    ports:
      - "1337:1337"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npm install && npm run build && NODE_ENV=production npm run start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/admin"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  nextjs:
    image: node:22
    working_dir: /srv/app
    volumes:
      - ./edx-fe:/srv/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - strapi
    command: sh -c "npm install && npm run build && NODE_ENV=production npm run start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    

